<?php

/**
 * Implements hook_help().
 */
function weather_app_theme($existing, $type, $theme, $path) {
    return [
        'weather-block' => [
            'variables' => [
                'temperatureMax' => NULL,
                'temperatureMin' => NULL,
                'humidity' => NULL,
                'snow' => NULL,
                'sunrise' => NULL,
                'sunset' => NULL,
                'cloudcover' => NULL,
            ],
        ],
    ];
}
